name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - run: bun test
